import {
    Activity,
    AlertTriangle,
    ArrowRightLeft,
    ArrowUpRight,
    Atom,
    BarChart,
    Beaker,
    Binary,
    BookA,
    BookOpen,
    BookType,
    Bot,
    Brain,
    Calculator,
    Circle,
    Coffee,
    Cpu,
    Crosshair,
    Dices,
    Dna,
    Droplet,
    Eye,
    Feather,
    FlaskConical,
    Gavel,
    GitCommit,
    GitMerge,
    Globe,
    Hash,
    Hexagon,
    History,
    Languages,
    Layers,
    LineChart,
    Link,
    Magnet,
    Mic2,
    Microscope,
    MoveHorizontal,
    Network,
    PenLine,
    PenTool,
    Recycle,
    RefreshCw,
    RotateCcw,
    Scale,
    Scissors,
    Scroll,
    ScrollText,
    Search,
    SearchCode,
    Shapes,
    Shield,
    ShieldCheck,
    Sigma,
    Sparkles,
    Star,
    TestTube,
    Thermometer,
    TreeDeciduous,
    Waves,
    Zap,
} from "lucide-react";

import { GymModuleConfig } from "../types/config";
import { GYM_IDS } from "./constants";

export const GYM_CATALOG: GymModuleConfig[] = [
    // --- SPECIALS ---
    {
        id: GYM_IDS.MIX_MATH,
        rttiType: "I",
        title: "Math Milkshake",
        description: "De ultieme mix van algebra, gonio en calculus.",
        icon: Dices,
        category: "math",
        isSpecial: true,
        themeColor: "amber",
        examDomain: "A",
        inputMode: "decimal",
        examWeight: 10
    },
    {
        id: GYM_IDS.MIX_PHYSICS,
        rttiType: "I",
        title: "Physics Milkshake",
        description: "Een brute mix van vectoren, circuits en eenheden.",
        icon: Atom,
        category: "physics",
        isSpecial: true,
        themeColor: "amber",
        examDomain: "A",
        inputMode: "decimal",
        examWeight: 10
    },
    {
        id: GYM_IDS.MIX_BIO,
        rttiType: "I",
        title: "Biology Milkshake",
        description: "Dwars door de matrix. Van molecuul tot biosfeer.",
        icon: TestTube,
        category: "biology",
        isSpecial: true,
        themeColor: "amber",
        examDomain: "A",
        inputMode: "text",
        examWeight: 10

    },
    {
        id: GYM_IDS.MIX_ENGLISH,
        rttiType: "I",
        title: "English Milkshake",
        description: "Idioms, connectors and text analysis.",
        icon: Languages,
        category: "english",
        isSpecial: true,
        themeColor: "amber",
        examDomain: "L-A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
    {
        id: GYM_IDS.MIX_PHILOSOPHY,
        rttiType: "I",
        title: "Socratic Milkshake",
        description: "Een mix van ethiek, techniek en argumentatie.",
        icon: Sparkles,
        category: "philosophy",
        isSpecial: true,
        themeColor: "purple",
        examDomain: "PH-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.MIX_FRENCH,
        rttiType: "I",
        title: "Café au Lait",
        description: "Een blend van grammatica, leesvaardigheid en literatuur.",
        icon: Coffee,
        category: "french",
        isSpecial: true,
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.MIX_DUTCH,
        rttiType: "I",
        title: "Koningsdag Mix",
        description: "Alles voor Nederlands VWO: Tekstbegrip en literatuur.",
        icon: Gavel,
        category: "dutch",
        isSpecial: true,
        themeColor: "orange",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.MIX_ECONOMICS,
        rttiType: "I",
        title: "The Invisible Hand",
        description: "Beheers de markt, inflatie en speltheorie.",
        icon: Scale,
        category: "economics",
        isSpecial: true,
        themeColor: "emerald",
        examDomain: "A",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.MIX_CHEMISTRY,
        rttiType: "I",
        title: "Scheikunde Shake",
        description: "Een explosieve mix van rekenen, organisch en redox.",
        icon: Beaker,
        category: "chemistry",
        isSpecial: true,
        themeColor: "indigo",
        examDomain: "A",
        inputMode: "decimal"
    },

    // --- MATH CORE ---
    {
        id: GYM_IDS.FRACTIONS,
        rttiType: "T1",
        title: "Breuken Breker",
        description: "Beheers rekenen met breuken, procenten en decimalen.",
        icon: RotateCcw,
        category: "math",
        themeColor: "orange",
        examDomain: "B",
        inputMode: "fraction"

    },
    {
        id: GYM_IDS.EXPONENTS,
        rttiType: "T1",
        title: "Machten Meester",
        description: "Machten, wortels en de rekenregels die je MOET kennen.",
        icon: Zap,
        category: "math",
        themeColor: "cyan",
        examDomain: "B",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.TRIG,
        rttiType: "T1",
        title: "Gonio Guru",
        description: "Sinus, cosinus en tangens. De cirkel is rond.",
        icon: Circle,
        category: "math",
        themeColor: "blue",
        examDomain: "D",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.DERIVS,
        rttiType: "T2",
        title: "Afgeleide Adelaar",
        description: "Differentiëren: van basisregels tot de kettingregel.",
        icon: GitCommit,
        category: "math",
        themeColor: "rose",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.FORMULAS,
        rttiType: "R",
        title: "Formule Fanaat",
        description: "Algebraïsch vaardig: omschrijven, substitueren en herleiden.",
        icon: Layers,
        category: "math",
        themeColor: "violet",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.VECTORS,
        rttiType: "T2",
        title: "Vector Vision",
        description: "Rekenen in 2D en 3D met vectoren en parameters.",
        icon: ArrowUpRight,
        category: "math",
        themeColor: "amber",
        examDomain: "E",
        inputMode: "decimal"

    },
    {
        id: GYM_IDS.INTEGRAAL,
        rttiType: "T2",
        title: "Intergraal Ninja",
        description: "Oppervlaktes en inhouden berekenen met integralen.",
        icon: Sigma,
        category: "math",
        themeColor: "lime",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.LIMITS,
        rttiType: "T2",
        title: "Limiet Luipaard",
        description: "Wat gebeurt er bij oneindig? Beheers de grenzen.",
        icon: ArrowRightLeft,
        category: "math",
        themeColor: "red",
        examDomain: "B",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.DOMAIN,
        rttiType: "T2",
        title: "Domein Detective",
        description: "Bereik, randpunten en domein bepalen van functies.",
        icon: ShieldCheck,
        category: "math",
        themeColor: "pink",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.GEOMETRY,
        rttiType: "T2",
        title: "Meetkunde Maestro",
        description: "Hoeken, afstanden en cirkelvergelijkingen.",
        icon: Shapes,
        category: "math",
        themeColor: "fuchsia",
        examDomain: "E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.STATS,
        rttiType: "T2",
        title: "Data Dominator",
        description: "Kansrekening, normale verdeling en binomiale toetsen.",
        icon: BarChart,
        category: "math",
        themeColor: "blue",
        examDomain: "A",
        inputMode: "decimal"
    },

    // --- PHYSICS CORE ---
    {
        id: GYM_IDS.UNITS,
        rttiType: "R",
        title: "Unit Unifier",
        description: "Metric conversions, SI-units, and orders of magnitude.",
        icon: Scale,
        category: "physics",
        themeColor: "blue",
        examDomain: "A",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.SIGFIG,
        rttiType: "R",
        title: "Digit Defender",
        description: "Master significant figures and scientific notation.",
        icon: Hash,
        category: "physics",
        themeColor: "emerald",
        examDomain: "A",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.ISOLATOR,
        rttiType: "T1",
        title: "Variable Void",
        description: "Isolating variables in complex physical formulas.",
        icon: MoveHorizontal,
        category: "physics",
        themeColor: "purple",
        examDomain: "A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.PHYS_VECTORS,
        rttiType: "T2",
        title: "Force Field",
        description: "Vector decomposition, resultant forces, and equilibrium.",
        icon: ArrowUpRight,
        category: "physics",
        themeColor: "rose",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.DECAY,
        rttiType: "R",
        title: "Radiation Radar",
        description: "Half-life, activity, and nuclear decay equations.",
        icon: Activity,
        category: "physics",
        themeColor: "amber",
        examDomain: "E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.CIRCUITS,
        rttiType: "T2",
        title: "Volt Viper",
        description: "Ohm's Law, Kirchhoff, and resistor networks.",
        icon: Cpu,
        category: "physics",
        themeColor: "cyan",
        examDomain: "D",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.GRAPH,
        rttiType: "T2",
        title: "Grafiek Goeroe",
        description: "(v,t) and (s,t) diagrams, slopes, and areas.",
        icon: LineChart,
        category: "physics",
        themeColor: "indigo",
        examDomain: "I",
        inputMode: "decimal"

    },
    {
        id: GYM_IDS.FLASHCARDS,
        rttiType: "R",
        title: "Knowledge Vault",
        description: "Core physics definitions and formula recall.",
        icon: BookOpen,
        category: "physics",
        themeColor: "teal",
        examDomain: "A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.GAS_LAW,
        rttiType: "T1",
        title: "Pressure Pro",
        description: "Ideal gas law (pV=nRT) and state changes.",
        icon: Thermometer,
        category: "physics",
        themeColor: "blue",
        examDomain: "B",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.MAGNETIC,
        rttiType: "T2",
        title: "Flux Finder",
        description: "B-fields, Lorentz force, and induction.",
        icon: Magnet,
        category: "physics",
        themeColor: "blue",
        examDomain: "D",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.MECHANICS_MASTER,
        rttiType: "T2",
        title: "Motion Master",
        description: "Kinematics: x(t), v(t), and constant acceleration.",
        icon: Activity,
        category: "physics",
        themeColor: "orange",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.MECHANICS_PRO,
        rttiType: "T2",
        title: "Dynamics Daddy",
        description: "Newton's laws, energy conservation, and power.",
        icon: Zap,
        category: "physics",
        themeColor: "red",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.OPTICS,
        rttiType: "T2",
        title: "Lens Legend",
        description: "Refraction, lenses, and ray tracing.",
        icon: Eye,
        category: "physics",
        themeColor: "cyan",
        examDomain: "B",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.ORBIT,
        rttiType: "T2",
        title: "Gravity God",
        description: "Kepler's laws, orbits, and celestial mechanics.",
        icon: Globe,
        category: "physics",
        themeColor: "blue",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.QUANTUM,
        rttiType: "I",
        title: "Photon Phreak",
        description: "Photoelectric effect, Bohr model, and wave-particle duality.",
        icon: Zap,
        category: "physics",
        themeColor: "purple",
        examDomain: "E",
        inputMode: "decimal",
        examWeight: 10
    },
    {
        id: GYM_IDS.WAVES,
        rttiType: "T2",
        title: "Sonic Sniper",
        description: "Waves, interference, and standing waves.",
        icon: Waves,
        category: "physics",
        themeColor: "blue",
        examDomain: "B",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.PARTICLE,
        rttiType: "R",
        title: "Deeltjes Dierentuin",
        description: "Standard model: Quarks, Leptons, and Bosons.",
        icon: Microscope,
        category: "physics",
        themeColor: "emerald",
        examDomain: "E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.ASTRO,
        rttiType: "R",
        title: "Sterrenkijker",
        description: "Astrophysics: HR-diagram, Life-cycle of stars, Big Bang.",
        icon: Star,
        category: "physics",
        themeColor: "amber",
        examDomain: "E",
        inputMode: "text"
    },

    // --- BIOLOGY CORE ---
    {
        id: GYM_IDS.PROTEIN,
        rttiType: "R",
        title: "Eiwit Codekraker",
        description: "Transcriptie, translatie en mutaties.",
        icon: Binary,
        category: "biology",
        themeColor: "emerald",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.BIO_ENERGY,
        rttiType: "T1",
        title: "ATP Centrale",
        description: "Fotosynthese en dissimilatie.",
        icon: Zap,
        category: "biology",
        themeColor: "amber",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.MEMBRANE,
        rttiType: "R",
        title: "Membraan Poortwachter",
        description: "Osmose, diffusie en actief transport.",
        icon: Droplet,
        category: "biology",
        themeColor: "blue",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.GENETICS,
        rttiType: "T2",
        title: "Mendel's Matrix",
        description: "Monohybride en dihybride kruisingen.",
        icon: Dna,
        category: "biology",
        themeColor: "emerald",
        examDomain: "C",
        inputMode: "text"
    },
    {
        id: GYM_IDS.NEURAL,
        rttiType: "T2",
        title: "Zenuwflits",
        description: "Actiepotentialen en synapsen.",
        icon: Network,
        category: "biology",
        themeColor: "indigo",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.HORMONE,
        rttiType: "T1",
        title: "Endocriene Regisseur",
        description: "Regelkringen en terugkoppeling.",
        icon: Scale,
        category: "biology",
        themeColor: "amber",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.IMMUNO,
        rttiType: "R",
        title: "Afweer Linie",
        description: "Specifieke en a-specifieke afweer.",
        icon: Shield,
        category: "biology",
        themeColor: "blue",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.NITROGEN,
        rttiType: "T1",
        title: "Stikstof Navigator",
        description: "De stikstofkringloop en bacteriële omzettingen.",
        icon: RefreshCw,
        category: "biology",
        themeColor: "blue",
        examDomain: "G",
        inputMode: "text"
    },
    {
        id: GYM_IDS.HARDY_WEINBERG,
        rttiType: "T2",
        title: "Hardy-Weinberg Helper",
        description: "Reken aan populatiegenetica en allelfrequenties.",
        icon: Calculator,
        category: "biology",
        themeColor: "emerald",
        examDomain: "F",
        inputMode: "decimal",
        rttiType: "T2"
    },
    {
        id: GYM_IDS.CIRCULATION,
        rttiType: "T1",
        title: "Hartslag Monitor",
        description: "Bloedsomloop, hartwerking en bloedvaten.",
        icon: Activity,
        category: "biology",
        themeColor: "rose",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.CELL_DIVISION,
        rttiType: "R",
        title: "Mito-Meio Meester",
        description: "Mitose, meiose en de celcyclus.",
        icon: TestTube,
        category: "biology",
        themeColor: "indigo",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.ENZYMES,
        rttiType: "T1",
        title: "Enzym Expert",
        description: "Slot-sleutel model en optimumkrommen.",
        icon: Scissors,
        category: "biology",
        themeColor: "teal",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.ECOLOGY,
        rttiType: "T1",
        title: "Eco Systeem",
        description: "Populatie-dynamiek, voedselwebben en successie.",
        icon: TreeDeciduous,
        category: "biology",
        themeColor: "emerald",
        examDomain: "G",
        inputMode: "text"
    },
    {
        id: GYM_IDS.FEEDBACK,
        rttiType: "T1",
        title: "Le Chatelier Bio",
        description: "Negatieve terugkoppeling en homeostase.",
        icon: Scale,
        category: "biology",
        themeColor: "amber",
        examDomain: "B",
        inputMode: "text"
    },

    // --- DUTCH CORE ---
    {
        id: GYM_IDS.SPELLING,
        rttiType: "T1",
        title: "Spelling Sniper",
        description: "Beheers d/t, koppelteken en hoofdletters.",
        icon: Crosshair,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.SENTENCE,
        rttiType: "T1",
        title: "Zinsontleder",
        description: "Onderwerp, gezegde en bepalingen.",
        icon: Binary,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.ARGUMENTATION,
        rttiType: "T2",
        title: "Drogreden Detector",
        description: "Fileer drogredenen en herken schema's.",
        icon: Gavel,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-C",
        inputMode: "text",
        rttiType: "T2"
    },
    {
        id: GYM_IDS.TEXT_ANATOMY,
        rttiType: "I",
        title: "Tekst Anatomie",
        description: "Signaalwoorden en tekstverbanden.",
        icon: Search,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.STYLE,
        rttiType: "T1",
        title: "Stijl Chirurg",
        description: "Elimineer pleonasmen en contaminaties.",
        icon: PenTool,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.LITERATURE,
        rttiType: "R",
        title: "Canon Kenner",
        description: "Van Middeleeuwen tot nu.",
        icon: Feather,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.VOCAB,
        rttiType: "R",
        title: "Woordschat",
        description: "Moeilijke woorden uit Cito-examens.",
        icon: BookA,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-A",
        inputMode: "text"
    },

    // --- CHEMISTRY CORE ---
    {
        id: GYM_IDS.MOL,
        rttiType: "T1",
        title: "Mol Master",
        description: "Stochiometrie: gram naar mol en vice versa.",
        icon: FlaskConical,
        category: "chemistry",
        themeColor: "indigo",
        examDomain: "C",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.PH,
        rttiType: "T1",
        title: "pH Precision",
        description: "Bereken pH van sterke en zwakke zuren/basen.",
        icon: Droplet,
        category: "chemistry",
        themeColor: "blue",
        examDomain: "D",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.REDOX,
        rttiType: "T1",
        title: "Electron Exchange",
        description: "Halfreacties en totaalreacties opstellen.",
        icon: Zap,
        category: "chemistry",
        themeColor: "amber",
        examDomain: "D",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.GREEN,
        rttiType: "T1",
        title: "Atom Economy",
        description: "E-factor en atoomeconomie berekeningen.",
        icon: Recycle,
        category: "chemistry",
        themeColor: "emerald",
        examDomain: "G",
        inputMode: "decimal"

    },
    {
        id: GYM_IDS.EQUILIBRIUM,
        rttiType: "T1",
        title: "Equilibrium Expert",
        description: "Evenwichtsvoorwaarden en Kc berekeningen.",
        icon: Scale,
        category: "chemistry",
        themeColor: "blue",
        examDomain: "D",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.ORGANIC,
        rttiType: "T1",
        title: "Nomenclatuur Ninja",
        description: "IUPAC naamgeving van organische verbindingen.",
        icon: Hexagon,
        category: "chemistry",
        themeColor: "indigo",
        examDomain: "E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.BONDING,
        rttiType: "T1",
        title: "Bonding Basics",
        description: "H-bruggen, vanderwaals en kookpunten.",
        icon: Link,
        category: "chemistry",
        themeColor: "blue",
        examDomain: "B",
        inputMode: "text"
    },
    {
        id: GYM_IDS.POLYMERS,
        rttiType: "T1",
        title: "Polymer Power",
        description: "Additie- en condensatiepolymerisatie.",
        icon: Scissors,
        category: "chemistry",
        themeColor: "indigo",
        examDomain: "E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.ENERGY,
        rttiType: "R",
        title: "Snelheids Duivel",
        description: "Reactiesnelheid en het botsende-deeltjesmodel.",
        icon: Activity,
        category: "chemistry",
        themeColor: "red",
        examDomain: "C",
        inputMode: "text"
    },
    {
        id: GYM_IDS.SPECTRO,
        rttiType: "I",
        title: "Spectra Sherlock",
        description: "Massaspectra, IR en NMR interpretatie.",
        icon: Search,
        category: "chemistry",
        themeColor: "purple",
        examDomain: "H",
        inputMode: "text"

    },

    // --- ENGLISH CORE ---
    {
        id: GYM_IDS.VOCAB_EN,
        rttiType: "R",
        title: "Lexicon Legend",
        description: "Academic English vocabulary for C1 level.",
        icon: BookA,
        category: "english",
        themeColor: "blue",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.GRAMMAR_PRO,
        rttiType: "T1",
        title: "Syntax Sniper",
        description: "Advanced tenses, conditionals, and passive voice.",
        icon: Languages,
        category: "english",
        themeColor: "blue",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.FORMAL_WRITER,
        rttiType: "T1",
        title: "Essay Engineer",
        description: "Linking words en formele formuleringen.",
        icon: PenTool,
        category: "english",
        themeColor: "blue",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.IRREGULAR_VERBS,
        rttiType: "R",
        title: "Irregular Verbs",
        description: "Become a master of 'go-went-gone'.",
        icon: RotateCcw,
        category: "english",
        themeColor: "blue",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.SENTENCE_SHIFTER,
        rttiType: "T1",
        title: "Sentence Shifter",
        description: "Active vs Passive, indirect speech.",
        icon: ArrowRightLeft,
        category: "english",
        themeColor: "blue",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.TONE_TUNER,
        rttiType: "I",
        title: "Tone Tuner",
        description: "Determine the writer's attitude.",
        icon: Mic2,
        category: "english",
        themeColor: "blue",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.COLLOCATION,
        rttiType: "T1",
        title: "Collocation King",
        description: "Master fixed word combinations.",
        icon: Link,
        category: "english",
        themeColor: "blue",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.LIT_HISTORY_EN,
        rttiType: "R",
        title: "Lit History",
        description: "From Shakespeare to the War Poets.",
        icon: History,
        category: "english",
        themeColor: "blue",
        examDomain: "L-E",
        inputMode: "text"
    },

    // --- PHILOSOPHY CORE ---
    {
        id: GYM_IDS.ETHICS,
        rttiType: "T2",
        title: "The Good Place",
        description: "Kant, Mill en Aristoteles. Plicht of Gevolg?",
        icon: Scale,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-B",
        inputMode: "text",
        rttiType: "T2"
    },
    {
        id: GYM_IDS.ANTHRO,
        rttiType: "T2",
        title: "Who Am I?",
        description: "Lichaam, Geest en Vrije Wil.",
        icon: Brain,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-C",
        inputMode: "text",
        rttiType: "T2"
    },
    {
        id: GYM_IDS.KNOWLEDGE,
        rttiType: "R",
        title: "Truth Seeker",
        description: "Kennisleer en Wetenschapsfilosofie.",
        icon: Microscope,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.TECH_MEDIATION,
        rttiType: "T2",
        title: "Cyborg Society",
        description: "Peter-Paul Verbeek en Mediatheorie.",
        icon: Bot,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.EXTENDED_MIND,
        rttiType: "I",
        title: "The Boundary Breaker",
        description: "Marc Slors & Enactivisme.",
        icon: Network,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.FALLACY,
        rttiType: "T2",
        title: "Drogreden Detector",
        description: "Fileer elk argument op foutieve logica.",
        icon: Gavel,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.SOURCE_DECODER,
        rttiType: "I",
        title: "Source Decoder",
        description: "Heidegger en Descartes vertalen.",
        icon: Scroll,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.EXAM_2025,
        rttiType: "I",
        title: "Examen 2025 Special",
        description: "Plessner, Foucault en de excentrische positie.",
        icon: ShieldCheck,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.EASTERN,
        rttiType: "R",
        title: "Oosterse Wijsheid",
        description: "Taoïsme, Boeddhisme en Confucianisme.",
        icon: Sparkles,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-E",
        inputMode: "text"

    },

    // --- FRENCH CORE ---
    {
        id: GYM_IDS.VOCAB_FR,
        rttiType: "R",
        title: "Vocabulaire Stratégique",
        description: "Cito-killers: Toutefois, Néanmoins, Susciter.",
        icon: BookType,
        category: "french",
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.CONJUGATION,
        rttiType: "T1",
        title: "Verbe Vitesse",
        description: "Subjonctif, Imparfait of Passé Composé?",
        icon: ScrollText,
        category: "french",
        themeColor: "rose",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.SUBJONCTIF,
        rttiType: "T1",
        title: "Subjonctif Sniper",
        description: "Beheers de uitzonderingen van de subjonctif.",
        icon: Crosshair,
        category: "french",
        themeColor: "rose",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.FALSE_FRIENDS,
        rttiType: "R",
        title: "Faux Amis",
        description: "Trap niet in de Franse instinkers.",
        icon: AlertTriangle,
        category: "french",
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.CONNECTOR,
        rttiType: "T1",
        title: "Connecteur Scanner",
        description: "En revanche, Par conséquent. Volg de rode draad.",
        icon: GitMerge,
        category: "french",
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.REFERENCE,
        rttiType: "T1",
        title: "Référence Radar",
        description: "Dont, Lequel, Celui-ci. Waar verwijst het naar?",
        icon: SearchCode,
        category: "french",
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.TONE_DETECTIVE,
        rttiType: "R",
        title: "Ton & Attitude",
        description: "Is de auteur sceptique of élogieux?",
        icon: Mic2,
        category: "french",
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text"
    },
    {
        id: GYM_IDS.LIT_HISTORY_FR,
        rttiType: "R",
        title: "Bibliothèque Élite",
        description: "Van Voltaire tot Camus. Stromingen en begrippen.",
        icon: Feather,
        category: "french",
        themeColor: "rose",
        examDomain: "L-E",
        inputMode: "text"
    },
    {
        id: GYM_IDS.ESSAY_EXPERT,
        rttiType: "T1",
        title: "Stylo Formel",
        description: "Formele brieven en betogen schrijven.",
        icon: PenLine,
        category: "french",
        themeColor: "rose",
        examDomain: "L-D",
        inputMode: "text"
    },
    {
        id: GYM_IDS.PRONOUN,
        rttiType: "T1",
        title: "Pronom Puzzle",
        description: "Lequel, duquel, auquel. Betrekkelijke vnw.",
        icon: SearchCode,
        category: "french",
        themeColor: "rose",
        examDomain: "L-D",
        inputMode: "text"
    },

    // --- INFINITE ENGINES ---
    {
        id: GYM_IDS.INFINITE_MATH,
        rttiType: "I",
        title: "Alpha Math AI",
        description: "De slimste wiskunde-assistent.",
        icon: Sparkles,
        category: "math",
        themeColor: "purple",
        examDomain: "A",
        inputMode: "decimal",
        examWeight: 10
    },
    {
        id: GYM_IDS.INFINITE_PHYSICS,
        rttiType: "I",
        title: "Gamma Physics AI",
        description: "Doorgrond de wetten van het universum.",
        icon: Sparkles,
        category: "physics",
        themeColor: "indigo",
        examDomain: "A",
        inputMode: "decimal"
    },
    {
        id: GYM_IDS.INFINITE_BIO,
        rttiType: "I",
        title: "Omega Bio AI",
        description: "Van DNA tot ecosystemen.",
        icon: Sparkles,
        category: "biology",
        themeColor: "emerald",
        examDomain: "A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
    {
        id: GYM_IDS.INFINITE_CHEMISTRY,
        rttiType: "I",
        title: "Bonding AI",
        description: "Chemische reacties en processen.",
        icon: Sparkles,
        category: "chemistry",
        themeColor: "blue",
        examDomain: "A",
        inputMode: "decimal",
        examWeight: 10
    },
    {
        id: GYM_IDS.INFINITE_HISTORY,
        rttiType: "I",
        title: "Chronos AI",
        description: "Beleef de geschiedenis opnieuw.",
        icon: History,
        category: "history",
        themeColor: "orange",
        examDomain: "A",
        inputMode: "text",
        examWeight: 7
    },
    {
        id: GYM_IDS.INFINITE_GEOGRAPHY,
        rttiType: "I",
        title: "Global Navigator",
        description: "Verken de aarde en haar systemen.",
        icon: Globe,
        category: "geography",
        themeColor: "blue",
        examDomain: "A",
        inputMode: "text",
        examWeight: 7
    },
    {
        id: GYM_IDS.INFINITE_ENGLISH,
        rttiType: "I",
        title: "Lexington AI",
        description: "Academic English mastery through infinite context.",
        icon: Languages,
        category: "english",
        themeColor: "blue",
        examDomain: "L-A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
    {
        id: GYM_IDS.INFINITE_FRENCH,
        rttiType: "I",
        title: "L'Expert AI",
        description: "Maîtrisez le français met oneindige Cito-stijl oefeningen.",
        icon: Languages,
        category: "french",
        themeColor: "rose",
        examDomain: "L-A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
    {
        id: GYM_IDS.INFINITE_DUTCH,
        rttiType: "I",
        title: "Tekst Titaan AI",
        description: "De ultieme tekst-analyse trainer voor het VWO examen.",
        icon: Search,
        category: "dutch",
        themeColor: "orange",
        examDomain: "L-A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
    {
        id: GYM_IDS.INFINITE_PHILOSOPHY,
        rttiType: "I",
        title: "Socratic AI",
        description: "Daag je denkvermogen uit met oneindige filosofische dilemma's.",
        icon: Brain,
        category: "philosophy",
        themeColor: "purple",
        examDomain: "PH-A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
    {
        id: GYM_IDS.INFINITE_ECONOMICS,
        rttiType: "I",
        title: "Global Markets AI",
        description: "Economics master via infinite AI-scenarios.",
        icon: LineChart,
        category: "economics",
        themeColor: "emerald",
        examDomain: "A",
        inputMode: "text",
        examWeight: 10,
        isReadingIntensive: true
    },
];
