import {
  absDependencies,
  addDependencies,
  compileDependencies,
  cosDependencies,
  create,
  detDependencies,
  eDependencies,
  evaluateDependencies,
  invDependencies,
  logDependencies,
  matrixDependencies,
  multiplyDependencies,
  parseDependencies,
  piDependencies,
  powDependencies,
  sinDependencies,
  sqrtDependencies,
  subtractDependencies,
  tanDependencies,
  traceDependencies,
  transposeDependencies,
} from "mathjs";

// Create a minimal mathjs instance with only the required dependencies.
// This prevents the entire library (including documentation and unused functions) from being bundled.
export const math = create({
  compileDependencies,
  evaluateDependencies,
  parseDependencies,
  detDependencies,
  invDependencies,
  transposeDependencies,
  traceDependencies,
  addDependencies,
  subtractDependencies,
  multiplyDependencies,
  matrixDependencies,
  absDependencies,
  sqrtDependencies,
  powDependencies,
  sinDependencies,
  cosDependencies,
  tanDependencies,
  logDependencies,
  piDependencies,
  eDependencies,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} as any); // deps are FactoryFunctionMap | undefined in mathjs v15 types
