export interface ArchNode {
  id: string;
  name: string;
  type: "feature" | "shared" | "component" | "api" | "lib" | "type";
  position: [number, number, number];
  color: string;
  description: string;
  files?: string[];
  children?: ArchNode[];
}

export const ARCHITECTURE_DATA: ArchNode[] = [
  {
    id: "exam",
    name: "Exam",
    type: "feature",
    position: [15, 6, 15],
    color: "#7B61FF",
    description: "Feature module: exam",
    files: [
      "src/features/exam/hooks/ExamContext.tsx",
      "src/features/exam/ui/modules/simulation/ExamSimulation.tsx",
      "src/features/exam/ui/ExamLayout.tsx",
    ],
  },
  {
    id: "math",
    name: "Math",
    type: "feature",
    position: [-15, 6, 15],
    color: "#00E5FF",
    description: "Feature module: math",
    files: [
      "src/features/math/hooks/MathLabContext.tsx",
      "src/features/math/hooks/MathLabContextInstance.ts",
      "src/features/math/hooks/useMathLabContext.ts",
      "src/features/math/ui/hub/HubView.tsx",
      "src/features/math/ui/modules/analytics/AnalyticsStage.tsx",
    ],
  },
  {
    id: "entities",
    name: "ENTITIES",
    type: "shared",
    position: [15, -8, 15],
    color: "#FFFFFF",
    description: "Core system layer: entities",
    files: [],
  },
  {
    id: "biology",
    name: "Biology",
    type: "feature",
    position: [15, 6, -15],
    color: "#BC13FE",
    description: "Feature module: biology",
    files: [
      "src/features/biology/hooks/BiologyLabContext.tsx",
      "src/features/biology/hooks/BiologyLabContextInstance.ts",
      "src/features/biology/hooks/useBiologyLabContext.ts",
      "src/features/biology/ui/modules/advanced/GelElectrophoresisSim.tsx",
      "src/features/biology/ui/modules/advanced/PcrSimulator.tsx",
    ],
  },
  {
    id: "voice-coach",
    name: "Voice-coach",
    type: "feature",
    position: [-3.43, 6, 15],
    color: "#FF9E00",
    description: "Feature module: voice-coach",
    files: [],
  },
  {
    id: "auth",
    name: "Auth",
    type: "feature",
    position: [-0.18, 6, 3.13],
    color: "#39FF14",
    description: "Feature module: auth",
    files: [],
  },
  {
    id: "settings",
    name: "Settings",
    type: "feature",
    position: [-9.87, 6, 9.78],
    color: "#00E5FF",
    description: "Feature module: settings",
    files: [
      "src/features/settings/hooks/SettingsContext.tsx",
      "src/features/settings/ui/SettingsLayout.tsx",
    ],
  },
  {
    id: "ai-lab",
    name: "Ai-lab",
    type: "feature",
    position: [15, 6, -15],
    color: "#00FFFF",
    description: "Feature module: ai-lab",
    files: [
      "src/features/ai-lab/hooks/AILabContext.tsx",
      "src/features/ai-lab/ui/AILabHub.tsx",
      "src/features/ai-lab/ui/AILabLayout.tsx",
    ],
  },
  {
    id: "api",
    name: "API",
    type: "api",
    position: [15, -6, -0.44],
    color: "#FFFFFF",
    description: "Core system layer: api",
    files: [],
  },
  {
    id: "usersettings",
    name: "Usersettings",
    type: "feature",
    position: [-10.19, 6, -0.78],
    color: "#00F5D4",
    description: "Feature module: usersettings",
    files: ["src/features/usersettings/ui/modules/MainUsersettingsLayout.tsx"],
  },
  {
    id: "lesson",
    name: "Lesson",
    type: "feature",
    position: [15, 6, 15],
    color: "#BC13FE",
    description: "Feature module: lesson",
    files: [],
  },
  {
    id: "philosophy",
    name: "Philosophy",
    type: "feature",
    position: [-6.24, 6, 6.17],
    color: "#FFFF00",
    description: "Feature module: philosophy",
    files: [
      "src/features/philosophy/hooks/PhilosophyLabContext.tsx",
      "src/features/philosophy/ui/modules/dialogue/DialogueStage.tsx",
      "src/features/philosophy/ui/modules/ethics/components/CasusSimulator.tsx",
      "src/features/philosophy/ui/modules/ethics/components/EthicsEngine.tsx",
      "src/features/philosophy/ui/modules/ethics/components/SJTStage.tsx",
    ],
  },
  {
    id: "pws",
    name: "Pws",
    type: "feature",
    position: [-15, 6, 2.86],
    color: "#7B61FF",
    description: "Feature module: pws",
    files: [],
  },
  {
    id: "rooster-scanner",
    name: "Rooster-scanner",
    type: "feature",
    position: [9.15, 6, 0.89],
    color: "#BC13FE",
    description: "Feature module: rooster-scanner",
    files: [],
  },
  {
    id: "debugger",
    name: "Debugger",
    type: "feature",
    position: [15, 6, -6.2],
    color: "#FF9E00",
    description: "Feature module: debugger",
    files: [],
  },
  {
    id: "calculator",
    name: "Calculator",
    type: "feature",
    position: [-15, 6, -3.53],
    color: "#00E5FF",
    description: "Feature module: calculator",
    files: [],
  },
  {
    id: "shared",
    name: "SHARED",
    type: "shared",
    position: [-5.38, -8, -15],
    color: "#FFFFFF",
    description: "Core system layer: shared",
    files: [],
  },
  {
    id: "library",
    name: "Library",
    type: "feature",
    position: [-15, 6, -15],
    color: "#FF00FF",
    description: "Feature module: library",
    files: [
      "src/features/library/hooks/LibraryContext.tsx",
      "src/features/library/ui/tabs/MondelingSimulator.tsx",
      "src/features/library/ui/ContextDock.tsx",
    ],
  },
  {
    id: "simulation",
    name: "Simulation",
    type: "feature",
    position: [-15, 6, 15],
    color: "#FFFF00",
    description: "Feature module: simulation",
    files: [
      "src/features/simulation/data/ChemistryEngine.ts",
      "src/features/simulation/data/RedoxEngine.ts",
      "src/features/simulation/ElectrochemistrySim.tsx",
      "src/features/simulation/KinematicsSim.tsx",
      "src/features/simulation/OpticsSim.tsx",
    ],
  },
  {
    id: "search",
    name: "Search",
    type: "feature",
    position: [4.52, 6, 8.13],
    color: "#FF00FF",
    description: "Feature module: search",
    files: [],
  },
  {
    id: "code",
    name: "Code",
    type: "feature",
    position: [-15, 6, -15],
    color: "#00F5D4",
    description: "Feature module: code",
    files: [
      "src/features/code/hooks/CodeLabContext.tsx",
      "src/features/code/ui/modules/python/PythonStage.tsx",
      "src/features/code/ui/CodeLabHub.tsx",
      "src/features/code/ui/CodeLabLayout.tsx",
    ],
  },
  {
    id: "planner",
    name: "Planner",
    type: "feature",
    position: [4.88, 6, 15],
    color: "#00F5D4",
    description: "Feature module: planner",
    files: [
      "src/features/planner/ui/modules/analytics/AnalyticsStage.tsx",
      "src/features/planner/ui/modules/calendar/CalendarStage.tsx",
      "src/features/planner/ui/modules/exams/ExamsStage.tsx",
      "src/features/planner/ui/modules/homework/HomeworkStage.tsx",
      "src/features/planner/ui/modules/pws/PWStage.tsx",
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    type: "feature",
    position: [15, 6, -15],
    color: "#FF3131",
    description: "Feature module: chemistry",
    files: [
      "src/features/chemistry/hooks/ChemistryLabContext.tsx",
      "src/features/chemistry/ui/modules/visualizer/VisualizerStage.tsx",
      "src/features/chemistry/ui/ChemistryLabLayout.tsx",
      "src/features/chemistry/utils/chemistryEngine.ts",
    ],
  },
  {
    id: "gamification",
    name: "Gamification",
    type: "feature",
    position: [-2.97, 6, -5.63],
    color: "#00FFFF",
    description: "Feature module: gamification",
    files: [],
  },
  {
    id: "brainstorm",
    name: "Brainstorm",
    type: "feature",
    position: [9.85, 6, 9.69],
    color: "#FF00FF",
    description: "Feature module: brainstorm",
    files: [
      "src/features/brainstorm/hooks/BrainstormLabContext.tsx",
      "src/features/brainstorm/ui/modules/knowledge/KnowledgeStage.tsx",
      "src/features/brainstorm/ui/modules/mindmap/MindMapStage.tsx",
      "src/features/brainstorm/ui/BrainstormHub.tsx",
      "src/features/brainstorm/ui/BrainstormLabLayout.tsx",
    ],
  },
  {
    id: "psychology",
    name: "Psychology",
    type: "feature",
    position: [1.52, 6, -15],
    color: "#FF9E00",
    description: "Feature module: psychology",
    files: [
      "src/features/psychology/hooks/PsychologyLabContext.tsx",
      "src/features/psychology/ui/modules/cognition/CognitionStage.tsx",
      "src/features/psychology/ui/modules/personality/PersonalityStage.tsx",
      "src/features/psychology/ui/modules/social/SocialStage.tsx",
      "src/features/psychology/ui/PsychologyHub.tsx",
    ],
  },
  {
    id: "app",
    name: "APP",
    type: "shared",
    position: [-15, -8, 8],
    color: "#FFFFFF",
    description: "Core system layer: app",
    files: [],
  },
  {
    id: "physics",
    name: "Physics",
    type: "feature",
    position: [15, 6, -15],
    color: "#FF3131",
    description: "Feature module: physics",
    files: [
      "src/features/physics/hooks/PhysicsLabContext.tsx",
      "src/features/physics/hooks/PhysicsLabContextInstance.ts",
      "src/features/physics/hooks/usePhysicsLabContext.ts",
      "src/features/physics/ui/gym/engines/flashcards/FlashcardEngine.ts",
      "src/features/physics/ui/gym/engines/CircuitEngine.ts",
    ],
  },
  {
    id: "language",
    name: "Language",
    type: "feature",
    position: [-15, 6, -8.56],
    color: "#39FF14",
    description: "Feature module: language",
    files: [
      "src/features/language/hooks/LanguageLabContext.tsx",
      "src/features/language/ui/modules/idioms/IdiomStage.tsx",
      "src/features/language/ui/modules/scenarios/ScenariosStage.tsx",
      "src/features/language/ui/modules/sjt/SJTStage.tsx",
      "src/features/language/ui/LanguageLabHub.tsx",
    ],
  },
  {
    id: "career",
    name: "Career",
    type: "feature",
    position: [15, 6, -15],
    color: "#FFFF00",
    description: "Feature module: career",
    files: ["src/features/career/lob/LOBContext.tsx"],
  },
  {
    id: "threed-studio",
    name: "Threed-studio",
    type: "feature",
    position: [-15, 6, 15],
    color: "#FF3131",
    description: "Feature module: threed-studio",
    files: [
      "src/features/threed-studio/hooks/ThreeDLabContext.tsx",
      "src/features/threed-studio/hooks/ThreeDLabContextInternal.ts",
      "src/features/threed-studio/hooks/useThreeDLabContext.ts",
      "src/features/threed-studio/stores/constructionStore.ts",
      "src/features/threed-studio/stores/spatialStore.ts",
    ],
  },
  {
    id: "research",
    name: "Research",
    type: "feature",
    position: [15, 6, 6.65],
    color: "#39FF14",
    description: "Feature module: research",
    files: [
      "src/features/research/hooks/ResearchContext.tsx",
      "src/features/research/ui/ResearchLayout.tsx",
    ],
  },
  {
    id: "quiz",
    name: "Quiz",
    type: "feature",
    position: [-15, 6, -15],
    color: "#00FFFF",
    description: "Feature module: quiz",
    files: [],
  },
];

export const CONNECTIONS: [string, string][] = [
  ["biology", "threed-studio"],
  ["career", "threed-studio"],
  ["career", "settings"],
  ["chemistry", "simulation"],
  ["chemistry", "threed-studio"],
  ["exam", "quiz"],
  ["lesson", "quiz"],
  ["library", "brainstorm"],
  ["library", "lesson"],
  ["math", "physics"],
  ["math", "threed-studio"],
  ["physics", "math"],
  ["physics", "threed-studio"],
  ["physics", "simulation"],
  ["simulation", "physics"],
  ["simulation", "threed-studio"],
  ["simulation", "chemistry"],
];
